### ISSUE TITLE
Integration of Langfuse has bugs

### ISSUE THREAD

**Issue by LiHongYan666** [langgenius/dify#8548] opened 2024-09-19 07:23 UTC
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Monitoring the integration of external Ops tools, there are bugs in the integration of Langfuse, see details:https://github.com/langfuse/langfuse/issues/2700

**Comment by ZhouhaoJiang** [comment] 2024-09-22 04:50
Please update the latest Dify version, this problem has been fixed in #7306 .

**Closed** 2024-09-23 08:30 UTC
Labels: 🐞 bug

**Comment by zolgear** [comment] 2024-09-23 11:26
Last week, I confirmed that the cost for Azure OpenAI GPT-4 was not being properly counted in the latest version. I believe we need to investigate the cause.

Dify v0.8.2
Langfuse v2.79.0

**Comment by marcklingen** [comment] 2024-09-23 12:10
-- Langfuse maintainer here

I'm happy to help figure this out. Generally token counts can be logged to langfuse directly which makes cost analysis the most reliable in langfuse. see docs page here for details: https://langfuse.com/docs/model-usage-and-cost

**Comment by zolgear** [comment] 2024-09-24 01:23
Sorry, the cost was being counted correctly!
(Dify 0.8.2 / Langufuse 2.81.0)

Tokens are counted immediately.
The cost could be confirmed on the Langufuse dashboard after 24 hours.

**Comment by luca1024-web** [comment] 2024-11-04 01:19
Is the problem solved? I have the same problem.

**Comment by marcklingen** [comment] 2024-11-04 19:22
great, thanks for confirming!
