### ISSUE TITLE
Unexpected problems encountered in the use of the knowledge base

### ISSUE THREAD

**Issue by shihuangzhe1235** [langgenius/dify#2721] opened 2024-03-06 13:03 UTC
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

BUG 1: The embedding model cannot be changed during the use of the knowledge base (even though the default embedding model has been changed, the embedding model in the knowledge base remains unchanged)
BUG 2: Knowledge base addition document does not perform QA mode when using high quality index, file upload fails when performing QA mode

**Comment by crazywoola** [comment] 2024-03-07 02:38
> BUG 1: The embedding model cannot be changed during the use of the knowledge base (even though the default embedding model has been changed, the embedding model in the knowledge base remains unchanged)
Actually, this is not a bug, this is by design, if you switch the model, the embedding itself has been changed, so the new model will not match the right one for future questions.

> BUG 2: Knowledge base addition document does not perform QA mode when using high quality index, file upload fails when performing QA mode

We have fixed in https://github.com/langgenius/dify/pull/2713

For bug report you should paste the error message or a screenshot at least. :)

**Closed by crazywoola** 2024-03-07 02:38 UTC
Labels: bug

**Comment by cxiaowen** [comment] 2025-02-06 07:48
{"message": "Internal Server Error", "code": "unknown"}         在调用接口插入时出现这个错误，状态码为500 ，
