### ISSUE TITLE
"Rerank Model is required", Can not publish app.

### ISSUE THREAD

**Issue by erigo** [langgenius/dify#7176] opened 2024-08-12 01:34 UTC
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a workflow app;
2. Add a Knowledge Retrieval Block
3. Add a Knowledge（use ECO Method） to the Block
4. Retrieval Setting use "Multi-path Retrieval"
5. Set the Rerank to off

### ✔️ Expected Behavior

Should Publish this app.

### ❌ Actual Behavior

The App can Run, bug can't Publish.

**Comment by crazywoola** [comment] 2024-08-12 01:45
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/25dde18a-98db-4fbb-a4bc-b11b79e90f30">
<img width="808" alt="image" src="https://github.com/user-attachments/assets/b7f3f895-548b-442d-af52-247ba28eb1eb">

I can not reproduce your problem.
If you chose 2 or more datasets, and the settings are different then the rerank model is required, I am not sure how you turn off the rerank model. Because we only weighted score or rerank model.

**Comment by erigo** [comment] 2024-08-12 02:26
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/29bbec1b-7e14-434e-a5a5-e5172fa8e51f">

**Comment by crazywoola** [comment] 2024-08-12 02:32
Can you give a screenshot of this one.

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/f8cab101-ad7c-4e27-ad6f-0b508cbe9402">

**Comment by erigo** [comment] 2024-08-12 02:34
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/467be53e-67da-41b9-90ec-6dce3e266a64">

**Comment by crazywoola** [comment] 2024-08-12 02:55
I tried this in the latest main branch. Still can not reproduce it, maybe you can try to upgrade new version later, in the meantime, you could try to create a new workflow to see if this persists.

**Comment by erigo** [comment] 2024-08-12 05:49
<img width="613" alt="image" src="https://github.com/user-attachments/assets/391f8466-d12e-4124-8f92-28958c5ce3f2">
I think it cause by this option.
When I use ECO Index Method, will produce the issue.

**Comment by crazywoola** [comment] 2024-08-12 09:17
Fixed in #7194

**Closed by crazywoola** 2024-08-12 09:17 UTC
Labels: 🐞 bug, 🤔 cant-reproduce
