### ISSUE TITLE
Bug Icon Provider

### ISSUE THREAD

**Issue by TienLD-0801** [langgenius/dify#5651] opened 2024-06-26 18:56 UTC
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

In the most recent commit update since the time I created the new issue, this icon is not working as expected, please reconsider.
<img width="1030" alt="Screenshot 2024-06-27 at 01 56 28" src="https://github.com/langgenius/dify/assets/112608271/c0088ec0-610a-42db-af3f-706620af6b4b">

**Comment by crazywoola** [comment] 2024-06-27 00:29
Can't reproduce on Cloud, I think this happens when you are trying to run from source code right?  Try to clean the browser cache and restart the api service again to see if this persists.

**Comment by TienLD-0801** [comment] 2024-06-27 02:29
@crazywoola I tried everything but it still doesn't work I think the problem comes from this pull request

**Comment by crazywoola** [comment] 2024-06-27 04:07
Which one. I have encountered this before long time ago, we just released model runtime that time. But it can't be reproduced now.

**Comment by TienLD-0801** [comment] 2024-06-27 04:22
@crazywoola  So is there any way to solve it? I cleared caching like you said but it doesn't work 
Maybe , Maybe the could urls are not working yet. 
Ex : https://cloud.dify.ai/console/api/workspaces/current/model-providers/openai/icon_large/en_US?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjhiZjMwZDYtZjcwMy00NzRkLTk2NjgtNDAwNGQ4OGQyMTIwIiwiZXhwIjoxNzIyMDU0MTI2LCJpc3MiOiJTRUxGX0hPU1RFRCIsInN1YiI6IkNvbnNvbGUgQVBJIFBhc3Nwb3J0In0.ZjSzZEGDihb4VimBTmY-OzexgItXcrv9t7xbQen1mIQ

**Comment by monotykamary** [comment] 2024-06-28 10:43
This also happens when self-hosting. It's an issue that probably occurs when you don't have an auth token on their cloud service

**Comment by monotykamary** [comment] 2024-06-28 16:17
It seems its more related how default values are generated for the environment variables. A quick workaround would be to explicitly set the domains yourself:
```
DOMAIN=https://example.com
CONSOLE_API_URL="$DOMAIN"
CONSOLE_WEB_URL="$DOMAIN"
SERVICE_API_URL="$DOMAIN"
APP_API_URL="$DOMAIN"
APP_WEB_URL="$DOMAIN"
```

**Comment by ugyuji** [comment] 2024-06-28 16:22
@monotykamary Thank you!
The same thing just happened with version 0.6.12 running on my local machine, and setting the domains explicitly just fixed the problem!

**Comment by tienldbnk** [comment] 2024-06-28 16:52
@monotykamary  @monotykamary  good idea , I think it works very well so I will close this issue

**Closed** 2024-06-28 16:53 UTC
Labels: 🐞 bug
