### ISSUE TITLE
When disabling the "Annotation Reply" button, the backend reports an error.

### ISSUE THREAD

**Issue by colvin777** [langgenius/dify#2904] opened 2024-03-19 14:43 UTC
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.9

### Cloud or Self Hosted

Cloud, Self Hosted (Source)

### Steps to reproduce

If there are no annotations, activating the "Annotation Reply" button does not create a collection in the vector database.
![image](https://github.com/langgenius/dify/assets/6747311/c91c173c-a268-4258-b146-0b38e25fb6c5)

If the "Annotation Reply" button is then turned off (without ever having created any annotations), the backend reports an error due to the absence of the corresponding collection name in the vector database.
![image](https://github.com/langgenius/dify/assets/6747311/717f1949-185c-4941-9ff9-293494fb904b)

### ✔️ Expected Behavior

disable_annotation_reply_task.py
to add a check for whether the annotations are empty:
    annotations_count = db.session.query(MessageAnnotation).filter(MessageAnnotation.app_id == app_id).count()

  if annotations_count > 0:
                vector = Vector(dataset, attributes=['doc_id', 'annotation_id', 'app_id'])
                vector.delete_by_metadata_field('app_id', app_id)

**Comment by crazywoola** [comment] 2024-03-20 01:31
Would you mind to submit a PR for this. Since you already located the root cause of this bug. I will invite you to the contributors' group after you open PRs. :) We will do alpha test in our contributors' group.

**Comment by JohnJyong** [comment] 2024-03-20 11:44
it has fixed by the PR https://github.com/langgenius/dify/pull/2877/files

**Closed** 2024-03-21 02:48 UTC
Labels: bug

**Comment by colvin777** [comment] 2024-03-21 14:40
> it has fixed by the PR https://github.com/langgenius/dify/pull/2877/files
this fix don't work when annotations is null
