### ISSUE TITLE
generate conversation title prompt sometimes may not works

### ISSUE THREAD

**Issue by waltcow** [langgenius/dify#1493] opened 2023-11-09 04:07 UTC
### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

here is error logs

![image](https://github.com/langgenius/dify/assets/3941174/2b10dc7e-bfab-42f5-97fe-cc26a634ceb1)

### ✔️ Expected Behavior

valid json result

### ❌ Actual Behavior

invalid json result

**Comment by takatost** [comment] 2023-11-21 06:03
Can you provide a way to reproduce it?

**Comment by crazywoola** [comment] 2023-12-19 11:20
Because some parameters was set up wrongly. See this PR for details https://github.com/langgenius/dify/pull/1718. I will close this issue if this persists, you can open another one.

**Closed by crazywoola** 2023-12-19 11:20 UTC
Labels: bug

**Comment by waltcow** [comment] 2023-12-19 13:37
This is related to the model ability, sometime model will not output valid json structure
