### ISSUE TITLE
Docker Compose deployment failed.

### ISSUE THREAD

**Issue by henrion-y** [langgenius/dify#5782] opened 2024-06-30 15:05 UTC
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="528" alt="b01d3ed1dbe0335e7740665e81b07d9" src="https://github.com/langgenius/dify/assets/30074062/be15155d-a05c-4233-8ceb-7666381755a9">

After executing the following commands:
```
cd docker
cp .env.example .env
docker compose up -d
```
an error is reported: "ERROR: Invalid interpolation format for 'opensearch' option in service 'services': 'discovery.type=${OPENSEARCH_DISCOVERY_TYPE:-single-node}'"

### ✔️ Expected Behavior

Normal updates to the operational Docker project.

### ❌ Actual Behavior

an error is reported: "ERROR: Invalid interpolation format for 'opensearch' option in service 'services': 'discovery.type=${OPENSEARCH_DISCOVERY_TYPE:-single-node}'"

**Comment by guchenhe** [comment] 2024-06-30 17:44
hi - thanks so much for the feedback. To make sure that custom configurations can be separated from `docker-compose.yaml` moving forward, the new docker file makes use of environment interpolation feature of docker compose. I suspect this may be due to how compose wrongly interprets the dash in the value `single-node`. 

A lot of environment interpolation related issues were ironed out in compose v2.11.2 (see: https://github.com/docker/compose/issues/9879). Could you try upgrading your compose to v2.11.2+ to see if this could be fixed?

**Comment by thenetguy** [comment] 2024-06-30 21:22
just tried to deploy via docker-compose up -d and got this error

```

$//' /docker-entrypoint.sh && chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh"cp /docker-entrypoint-mount.sh /docker-entrypoint.sh && sed -i 's/`
```

and no i dont want to try docker compose v2 .

**Comment by guchenhe** [comment] 2024-06-30 21:58
> just tried to deploy via docker-compose up -d and got this error
> 
> ```
> 
> $//' /docker-entrypoint.sh && chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh"cp /docker-entrypoint-mount.sh /docker-entrypoint.sh && sed -i 's/`
> ```
> 
> and no i dont want to try docker compose v2 .

this seems like a different error - please open another issue with the full log of the error message

**Comment by thenetguy** [comment] 2024-06-30 22:15
that is all the output i get from docker-compose up -d there arent any other logs. steps to reproduce,

1. clone the repo
2. cd into the repo
3. cd docker
4. cp .env.example .env
5. docker compose up -d

**Comment by simplast** [comment] 2024-07-01 01:37
sudo docker compose pull
---
invalid interpolation format for services.ssrf_proxy.entrypoint.[]: "cp /docker-entrypoint-mount.sh /docker-entrypoint.sh && sed -i 's/\r$//' /docker-entrypoint.sh && chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh". You may need to escape any $ with another $

**Comment by takatost** [comment] 2024-07-01 06:50
Hey @henrion-y @thenetguy @simplast, the issue's fixed now. You can pull the latest code from the main branch and try redeploying.

**Comment by big-pan-whu** [comment] 2024-07-04 08:55
> Hey @henrion-y @thenetguy @simplast, the issue's fixed now. You can pull the latest code from the main branch and try redeploying.

I pull the latest code and try redeploying, It takes timeout error:error pulling image configuration: download failed after attempts=6: dial tcp 173.252.105.21:443: i/o timeout

**Comment by crazywoola** [comment] 2024-07-10 12:11
> > Hey @henrion-y @thenetguy @simplast, the issue's fixed now. You can pull the latest code from the main branch and try redeploying.
> 
> I pull the latest code and try redeploying, It takes timeout error:error pulling image configuration: download failed after attempts=6: dial tcp 173.252.105.21:443: i/o timeout

This is a general network issue.

**Closed** 2024-08-13 07:03 UTC
Labels: 🐞 bug, no-issue-activity
