### ISSUE TITLE
Image url not working

### ISSUE THREAD

**Issue by xfanwu** [langgenius/dify#10169] opened 2024-11-01 09:56 UTC
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Cloud latest

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I've set up an optional image input in my chat flow, but I'm encountering an error when pasting URLs from Firebase Storage. 
I've tested with various images from different buckets, but the issue persists. I don't believe it's related to Firebase, but I haven't been able to reproduce the issue with other services.

Here's an example URL causing the problem:
`https://firebasestorage.googleapis.com/v0/b/chance-app-7b166.appspot.com/o/test%2F%E4%B8%8B%E8%BD%BD%20(1).jpeg?alt=media&token=19cddfa5-d594-467f-a171-a45020289736`

<img width="317" alt="image" src="https://github.com/user-attachments/assets/a657e720-ae61-4727-86ae-b55544cca231">

### ✔️ Expected Behavior

The url should be passed into the flow

### ❌ Actual Behavior

Error encountered.

**Comment by laipz8200** [comment] 2024-11-01 11:26
This issue was caused by our CSP, but it's already fixed in our main branch. Just hang tight while we finish testing, and it will be updated to the Cloud version soon!

**Closed** 2024-11-01 11:26 UTC
Labels: 🐞 bug

**Comment by xfanwu** [comment] 2024-11-02 11:04
@laipz8200 Thank you for the prompt reply. I was wondering if there’s a schedule for when the fix will be updated. Our app relies on this bug fix, so any information on the timeline would be greatly appreciated.

**Comment by laipz8200** [comment] 2024-11-02 11:20
> @laipz8200 Thank you for the prompt reply.
> 
> There is another error when use the 'upload file' s' image.url. Is it a known issue as well?
> <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/6542647/382466661-3f86ee4e-e253-481c-a48c-411a39497640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDY1MTcsIm5iZiI6MTczMDU0NjIxNywicGF0aCI6Ii82NTQyNjQ3LzM4MjQ2NjY2MS0zZjg2ZWU0ZS1lMjUzLTQ4MWMtYTQ4Yy00MTFhMzk0OTc2NDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDJUMTExNjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2FkZTI5Yjk2Mzc4OWNlNzg5MGEwZTA5MzljMTI0ZmMzMGI5YjMzM2Q0MGIyM2Y5MmFkMmU2MjNiMWQwMjZlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.DFkXhxw5ynpNz61QJAbnRqZu7MZsf9bzDM9obtuge5c">
> 
> I was wondering if there’s a schedule for when the fix will be updated. Our app relies on this bug fix, so any information on the timeline would be greatly appreciated.

We don't support using the file's signed URL (visible in the log panel). The file.url property refers to the remote_url and only exists when a file is uploaded via a link.

**Comment by viniciustrndd** [comment] 2024-11-05 03:11
@laipz8200, When I use markdown, it logs correctly:

{
  "answer": "Great! Here are some compositions with the clay seagulls:\n\n![Composition with 2G and 1P](https://xtrategiadigital.com.br/wp-content/uploads/2024/11/gaivotas-2G1P-.jpg)\n\n![Composition with 4G and 2P](https://xtrategiadigital.com.br/wp-content/uploads/2024/11/gaivotas-4g2p.jpeg)\n\n![Composition with 4G and 6P](https://xtrategiadigital.com.br/wp-content/uploads/2024/11/gaivotas-4G6P.jpeg)\n\nThese handcrafted pieces bring a special touch and can fit into various decoration styles. Did any of these compositions catch your attention? 😊",
  "files": []
}

But in the viewer, the image does not appear or load:

![Captura de Tela 2024-11-05 às 00 08 31](https://github.com/user-attachments/assets/6d1c38a5-7634-4f03-bd20-9e6de4a02477)
