### ISSUE TITLE
Feature Request: Add "Parallel" Execution Capability to the LLM Module

### ISSUE THREAD

**Issue by zhangeden** [langgenius/dify#7844] opened 2024-08-30 11:45 UTC
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I often design workflows that are quite complex, involving dozens to hundreds of LLM calls. Some of these LLM calls have parallel relationships, and if they could be executed simultaneously, it would significantly speed up the overall process.

Specifically, I suggest the following:

Allow LLMs to be configured for either parallel or sequential execution modes. In parallel mode, multiple LLMs can run simultaneously and produce results concurrently.
(Key Suggestion) Introduce a parallel execution mode within the iteration functionality.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by QuietRocket** [comment] 2024-08-30 12:08
Seems like a dupe of #4275?

**Comment by crazywoola** [comment] 2024-08-30 12:32
Will be released in v0.8

**Closed by crazywoola** 2024-08-30 12:32 UTC
Labels: 💪 enhancement, 🌊 feat:workflow
